export const GET_MOVIE_LIST_REQUEST ='GET_MOVIE_LIST_REQUEST';
export const GET_MOVIE_DETAIL_REQUEST = 'GET_MOVIE_DETAIL_REQUEST';
export const REQUEST_FAILURE='REQUEST_FAILURE';
export const FETCH_REQUEST='FETCH_REQUEST';